import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import Overlay from "@/components/ui/overlay";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className='antialiased'
      >
        <main>{children}</main>
        <Toaster position="top-center" richColors closeButton />
        <Overlay />
      </body>
    </html>
  );
}
